version: '1'

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_PORT: 3000
      DB_USER: ${DB_USER}
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASSWD}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_ENV: ${APP_ENV}
    links:
      - database:database
    volumes:
      - .:/app
      - ${HOME}:/root
    ports:
      - 8080:8080