version: '1'

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
  rabbit:
    image: rabbitmq:3.12
    ports:
      # MQTT ws port
      - 15675:15675
      # AMQP 
      - 5672:5672
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DB=menu
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
      - GF_SERVER_HTTP_PORT=2345
    ports:
      - '2345:2345'
    volumes:
      - grafana-storage:/var/lib/grafana
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASSWD}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_ENV: ${APP_ENV}
      TOKEN_EXPIRE_HOURS: ${TOKEN_EXPIRE_HOURS}
      TOKEN_SECRET: ${TOKEN_SECRET}
    links:
      - database:database
    volumes:
      - .:/app
      - ${HOME}:/root
    ports:
      - 8080:8080
volumes:
  grafana-storage: { }