version: '1'

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
  rabbit:
    image: rabbitmq:3.12
    ports:
      # MQTT ws port
      - 15675:15675
      # AMQP 
      - 5672:5672
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASSWD}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_ENV: ${APP_ENV}
      TOKEN_EXPIRE_HOURS: ${TOKEN_EXPIRE_HOURS}
      TOKEN_SECRET: ${TOKEN_SECRET}
    links:
      - database:database
    volumes:
      - .:/app
      - ${HOME}:/root
    ports:
      - 8080:8080